var TRANSLATIONS = {
  en: {
    nav: { courses: 'Courses', about: 'About', contact: 'Contact', blog: 'Blog', bookCta: 'Book a Tee Time Now!' },
    hero: { title1: 'Book Golf Tee Times', title2: 'in Catalunya', subtitle: '20 premier courses from Barcelona to Costa Brava. Championship layouts, coastal gems, and mountain retreats. Green fees from EUR 35.', cta: 'Explore Golf Courses' },
    about: { subtitle: 'Your Gateway to Golf in Catalunya', description: 'Catalunya is home to some of Europe\'s most spectacular golf courses, from the world-renowned Camiral Resort (formerly PGA Catalunya) to hidden gems nestled along the Costa Brava coastline. With 20 courses spanning Barcelona, Girona, Tarragona, and the Pyrenees, we make booking your perfect round effortless.', feat1Title: '20 Premier Courses', feat1Text: 'Championship courses, coastal layouts, and mountain retreats across Catalunya.', feat2Title: 'Instant Confirmation', feat2Text: 'Book online and receive instant confirmation. No waiting, no phone calls.', feat3Title: 'Best Rate Guarantee', feat3Text: 'We negotiate directly with courses to offer the best green fee rates. From EUR 35.' },
    courses: { title: 'Golf Courses in Catalunya', subtitle: 'From Barcelona to the Pyrenees, discover and book tee times at the finest courses in the region. Hover the cards for details and booking links.', holes: 'Holes', par: 'Par', hover: 'Hover for details', bookBtn: 'Book a Tee Time Now', detailsBtn: 'View Course Details' },
    cta: { title: 'Ready to Play?', subtitle: 'Choose from 20 premier courses across Catalunya. Instant confirmation, best rates, and local expertise.', bookBtn: 'Book a Tee Time Now', contactBtn: 'Contact Us' },
    contact: { title: 'Get in Touch', email: 'Email', phone: 'Phone', location: 'Location' },
    footer: { description: 'Book golf tee times across Catalunya with ease. We cover all major golfing regions including Barcelona, Costa Brava, Girona, Tarragona, and the Pyrenees \u2013 20 premium courses at your fingertips.', quickLinks: 'Quick Links', services: 'Services', contactInfo: 'Contact Info', home: 'Home', golfCourses: 'Golf Courses', bookTee: 'Book Tee Times in Catalunya', copyright: 'All rights reserved.', privacy: 'Privacy Policy', terms: 'Terms of Service' },
    cookie: { text: 'This website uses cookies to ensure you get the best experience.', learn: 'Learn more', accept: 'Accept', prefs: 'Preferences' },
    blog: { subtitle: 'Catalunya Golf Guide', title: 'Tips, Course Guides & Travel Advice', description: 'Expert golf travel tips, detailed course guides, and insider advice for planning your perfect Catalunya golf holiday.', readMore: 'Read More', noPosts: 'No blog posts yet. Check back soon!' },
    scroll: 'Scroll'
  },
  es: {
    nav: { courses: 'Campos', about: 'Nosotros', contact: 'Contacto', blog: 'Blog', bookCta: 'Reservar Tee Time' },
    hero: { title1: 'Reserva Tee Times de Golf', title2: 'en Catalunya', subtitle: '20 campos de primer nivel desde Barcelona hasta la Costa Brava. Recorridos de campeonato, joyas costeras y retiros de monta\u00f1a. Green fees desde 35 EUR.', cta: 'Explorar Campos de Golf' },
    about: { subtitle: 'Tu puerta al Golf en Catalunya', description: 'Catalunya alberga algunos de los campos de golf m\u00e1s espectaculares de Europa, desde el mundialmente famoso Camiral Resort (antes PGA Catalunya) hasta joyas ocultas a lo largo de la Costa Brava. Con 20 campos en Barcelona, Girona, Tarragona y los Pirineos, reservar tu ronda perfecta es muy f\u00e1cil.', feat1Title: '20 Campos Premium', feat1Text: 'Campos de campeonato, recorridos costeros y retiros de monta\u00f1a en toda Catalunya.', feat2Title: 'Confirmaci\u00f3n Instant\u00e1nea', feat2Text: 'Reserva online y recibe confirmaci\u00f3n al instante. Sin esperas, sin llamadas.', feat3Title: 'Mejor Precio Garantizado', feat3Text: 'Negociamos directamente con los campos para ofrecer las mejores tarifas. Desde 35 EUR.' },
    courses: { title: 'Campos de Golf en Catalunya', subtitle: 'De Barcelona a los Pirineos, descubre y reserva tee times en los mejores campos de la regi\u00f3n.', holes: 'Hoyos', par: 'Par', hover: 'Pasar el cursor para detalles', bookBtn: 'Reservar Tee Time', detailsBtn: 'Ver Detalles del Campo' },
    cta: { title: '\u00bfListo para Jugar?', subtitle: 'Elige entre 20 campos premium en Catalunya. Confirmaci\u00f3n instant\u00e1nea, mejores tarifas y experiencia local.', bookBtn: 'Reservar Tee Time', contactBtn: 'Cont\u00e1ctanos' },
    contact: { title: 'Ponte en Contacto', email: 'Correo', phone: 'Tel\u00e9fono', location: 'Ubicaci\u00f3n' },
    footer: { description: 'Reserva tee times de golf en Catalunya con facilidad. Cubrimos todas las regiones incluyendo Barcelona, Costa Brava, Girona, Tarragona y los Pirineos \u2013 20 campos premium a tu alcance.', quickLinks: 'Enlaces R\u00e1pidos', services: 'Servicios', contactInfo: 'Informaci\u00f3n de Contacto', home: 'Inicio', golfCourses: 'Campos de Golf', bookTee: 'Reservar Tee Times en Catalunya', copyright: 'Todos los derechos reservados.', privacy: 'Pol\u00edtica de Privacidad', terms: 'T\u00e9rminos de Servicio' },
    cookie: { text: 'Este sitio web usa cookies para asegurar la mejor experiencia.', learn: 'Saber m\u00e1s', accept: 'Aceptar', prefs: 'Preferencias' },
    blog: { subtitle: 'Gu\u00eda de Golf Catalunya', title: 'Consejos, Gu\u00edas de Campos y Viajes', description: 'Consejos expertos de viajes de golf, gu\u00edas detalladas de campos e informaci\u00f3n privilegiada para planificar tu vacaci\u00f3n de golf en Catalunya.', readMore: 'Leer M\u00e1s', noPosts: 'A\u00fan no hay publicaciones. \u00a1Vuelve pronto!' },
    scroll: 'Despl\u00e1zate'
  },
  ca: {
    nav: { courses: 'Camps', about: 'Nosaltres', contact: 'Contacte', blog: 'Blog', bookCta: 'Reservar Tee Time' },
    hero: { title1: 'Reserva Tee Times de Golf', title2: 'a Catalunya', subtitle: '20 camps de primer nivell des de Barcelona fins a la Costa Brava. Recorreguts de campionat, joies costaneres i retirs de muntanya. Green fees des de 35 EUR.', cta: 'Explorar Camps de Golf' },
    about: { subtitle: 'La teva porta al Golf a Catalunya', description: 'Catalunya \u00e9s la llar d\'alguns dels camps de golf m\u00e9s espectaculars d\'Europa, des del reconegut Camiral Resort (abans PGA Catalunya) fins a joies ocultes al llarg de la Costa Brava. Amb 20 camps a Barcelona, Girona, Tarragona i els Pirineus, reservar la teva ronda perfecta \u00e9s molt f\u00e0cil.', feat1Title: '20 Camps Premium', feat1Text: 'Camps de campionat, recorreguts costaners i retirs de muntanya a tota Catalunya.', feat2Title: 'Confirmaci\u00f3 Instant\u00e0nia', feat2Text: 'Reserva online i rep confirmaci\u00f3 a l\'instant. Sense esperes, sense trucades.', feat3Title: 'Millor Preu Garantit', feat3Text: 'Negociem directament amb els camps per oferir les millors tarifes. Des de 35 EUR.' },
    courses: { title: 'Camps de Golf a Catalunya', subtitle: 'De Barcelona als Pirineus, descobreix i reserva tee times als millors camps de la regi\u00f3.', holes: 'Forats', par: 'Par', hover: 'Passa el cursor per detalls', bookBtn: 'Reservar Tee Time', detailsBtn: 'Veure Detalls del Camp' },
    cta: { title: 'Preparat per Jugar?', subtitle: 'Tria entre 20 camps premium a Catalunya. Confirmaci\u00f3 instant\u00e0nia, millors tarifes i experi\u00e8ncia local.', bookBtn: 'Reservar Tee Time', contactBtn: 'Contacta\'ns' },
    contact: { title: 'Posa\'t en Contacte', email: 'Correu', phone: 'Tel\u00e8fon', location: 'Ubicaci\u00f3' },
    footer: { description: 'Reserva tee times de golf a Catalunya amb facilitat. Cobrim totes les regions incloent Barcelona, Costa Brava, Girona, Tarragona i els Pirineus \u2013 20 camps premium al teu abast.', quickLinks: 'Enlla\u00e7os R\u00e0pids', services: 'Serveis', contactInfo: 'Informaci\u00f3 de Contacte', home: 'Inici', golfCourses: 'Camps de Golf', bookTee: 'Reservar Tee Times a Catalunya', copyright: 'Tots els drets reservats.', privacy: 'Pol\u00edtica de Privacitat', terms: 'Termes de Servei' },
    cookie: { text: 'Aquest lloc web fa servir galetes per assegurar la millor experi\u00e8ncia.', learn: 'Saber m\u00e9s', accept: 'Acceptar', prefs: 'Prefer\u00e8ncies' },
    blog: { subtitle: 'Guia de Golf Catalunya', title: 'Consells, Guies de Camps i Viatges', description: 'Consells experts de viatges de golf, guies detallades de camps i informaci\u00f3 privilegiada per planificar les teves vacances de golf a Catalunya.', readMore: 'Llegir M\u00e9s', noPosts: 'Encara no hi ha publicacions. Torna aviat!' },
    scroll: 'Despla\u00e7a\'t'
  },
  de: {
    nav: { courses: 'Golfpl\u00e4tze', about: '\u00dcber uns', contact: 'Kontakt', blog: 'Blog', bookCta: 'Tee Time buchen' },
    hero: { title1: 'Golf Tee Times buchen', title2: 'in Katalonien', subtitle: '20 erstklassige Golfpl\u00e4tze von Barcelona bis zur Costa Brava. Championship-Layouts, K\u00fcstenperlen und Bergrefugien. Green Fees ab 35 EUR.', cta: 'Golfpl\u00e4tze entdecken' },
    about: { subtitle: 'Ihr Tor zum Golf in Katalonien', description: 'Katalonien beherbergt einige der spektakul\u00e4rsten Golfpl\u00e4tze Europas, vom weltber\u00fchmten Camiral Resort (ehemals PGA Catalunya) bis zu versteckten Juwelen an der Costa Brava. Mit 20 Pl\u00e4tzen in Barcelona, Girona, Tarragona und den Pyren\u00e4en machen wir die Buchung Ihrer perfekten Runde m\u00fchelos.', feat1Title: '20 Premium Golfpl\u00e4tze', feat1Text: 'Championship-Pl\u00e4tze, K\u00fcstenanlage und Bergrefugien in ganz Katalonien.', feat2Title: 'Sofortige Best\u00e4tigung', feat2Text: 'Online buchen und sofortige Best\u00e4tigung erhalten. Kein Warten, keine Anrufe.', feat3Title: 'Bestpreis-Garantie', feat3Text: 'Wir verhandeln direkt mit den Pl\u00e4tzen f\u00fcr die besten Green Fee Preise. Ab 35 EUR.' },
    courses: { title: 'Golfpl\u00e4tze in Katalonien', subtitle: 'Von Barcelona bis zu den Pyren\u00e4en \u2013 entdecken und buchen Sie Tee Times auf den besten Pl\u00e4tzen der Region.', holes: 'L\u00f6cher', par: 'Par', hover: 'Hover f\u00fcr Details', bookBtn: 'Tee Time buchen', detailsBtn: 'Platzdetails ansehen' },
    cta: { title: 'Bereit zu spielen?', subtitle: 'W\u00e4hlen Sie aus 20 Premium-Golfpl\u00e4tzen in Katalonien. Sofortige Best\u00e4tigung, beste Preise und lokale Expertise.', bookBtn: 'Tee Time buchen', contactBtn: 'Kontaktieren Sie uns' },
    contact: { title: 'Kontaktieren Sie uns', email: 'E-Mail', phone: 'Telefon', location: 'Standort' },
    footer: { description: 'Buchen Sie Golf Tee Times in Katalonien mit Leichtigkeit. Wir decken alle Golfregionen ab, einschlie\u00dflich Barcelona, Costa Brava, Girona, Tarragona und die Pyren\u00e4en \u2013 20 Premium-Pl\u00e4tze griffbereit.', quickLinks: 'Schnelllinks', services: 'Dienstleistungen', contactInfo: 'Kontaktinformationen', home: 'Startseite', golfCourses: 'Golfpl\u00e4tze', bookTee: 'Tee Times in Katalonien buchen', copyright: 'Alle Rechte vorbehalten.', privacy: 'Datenschutz', terms: 'Nutzungsbedingungen' },
    cookie: { text: 'Diese Website verwendet Cookies, um Ihnen das beste Erlebnis zu bieten.', learn: 'Mehr erfahren', accept: 'Akzeptieren', prefs: 'Einstellungen' },
    blog: { subtitle: 'Katalonien Golf Guide', title: 'Tipps, Platzf\u00fchrer & Reiseberatung', description: 'Experten-Golfreisetipps, detaillierte Platzf\u00fchrer und Insider-Tipps f\u00fcr die Planung Ihres perfekten Katalonien-Golfurlaubs.', readMore: 'Weiterlesen', noPosts: 'Noch keine Beitr\u00e4ge. Schauen Sie bald wieder vorbei!' },
    scroll: 'Scrollen'
  },
  fr: {
    nav: { courses: 'Parcours', about: '\u00c0 propos', contact: 'Contact', blog: 'Blog', bookCta: 'R\u00e9server un Tee Time' },
    hero: { title1: 'R\u00e9servez des Tee Times', title2: 'en Catalogne', subtitle: '20 parcours de premier plan de Barcelone \u00e0 la Costa Brava. Parcours de championnat, joyaux c\u00f4tiers et retraites de montagne. Green fees \u00e0 partir de 35 EUR.', cta: 'D\u00e9couvrir les Parcours' },
    about: { subtitle: 'Votre porte vers le Golf en Catalogne', description: 'La Catalogne abrite certains des parcours de golf les plus spectaculaires d\'Europe, du c\u00e9l\u00e8bre Camiral Resort (anciennement PGA Catalunya) aux joyaux cach\u00e9s le long de la Costa Brava. Avec 20 parcours \u00e0 Barcelone, G\u00e9rone, Tarragone et dans les Pyr\u00e9n\u00e9es, r\u00e9server votre partie parfaite n\'a jamais \u00e9t\u00e9 aussi facile.', feat1Title: '20 Parcours Premium', feat1Text: 'Parcours de championnat, trac\u00e9s c\u00f4tiers et retraites de montagne dans toute la Catalogne.', feat2Title: 'Confirmation Instantan\u00e9e', feat2Text: 'R\u00e9servez en ligne et recevez une confirmation instantan\u00e9e. Pas d\'attente, pas d\'appels.', feat3Title: 'Meilleur Prix Garanti', feat3Text: 'Nous n\u00e9gocions directement avec les parcours pour offrir les meilleurs tarifs. D\u00e8s 35 EUR.' },
    courses: { title: 'Parcours de Golf en Catalogne', subtitle: 'De Barcelone aux Pyr\u00e9n\u00e9es, d\u00e9couvrez et r\u00e9servez des tee times sur les meilleurs parcours de la r\u00e9gion.', holes: 'Trous', par: 'Par', hover: 'Survoler pour les d\u00e9tails', bookBtn: 'R\u00e9server un Tee Time', detailsBtn: 'Voir les d\u00e9tails' },
    cta: { title: 'Pr\u00eat \u00e0 jouer ?', subtitle: 'Choisissez parmi 20 parcours premium en Catalogne. Confirmation instantan\u00e9e, meilleurs tarifs et expertise locale.', bookBtn: 'R\u00e9server un Tee Time', contactBtn: 'Nous contacter' },
    contact: { title: 'Contactez-nous', email: 'E-mail', phone: 'T\u00e9l\u00e9phone', location: 'Adresse' },
    footer: { description: 'R\u00e9servez des tee times de golf en Catalogne en toute simplicit\u00e9. Nous couvrons toutes les r\u00e9gions, y compris Barcelone, Costa Brava, G\u00e9rone, Tarragone et les Pyr\u00e9n\u00e9es \u2013 20 parcours premium \u00e0 port\u00e9e de main.', quickLinks: 'Liens Rapides', services: 'Services', contactInfo: 'Coordonn\u00e9es', home: 'Accueil', golfCourses: 'Parcours de Golf', bookTee: 'R\u00e9server des Tee Times en Catalogne', copyright: 'Tous droits r\u00e9serv\u00e9s.', privacy: 'Politique de confidentialit\u00e9', terms: 'Conditions d\'utilisation' },
    cookie: { text: 'Ce site utilise des cookies pour vous garantir la meilleure exp\u00e9rience.', learn: 'En savoir plus', accept: 'Accepter', prefs: 'Pr\u00e9f\u00e9rences' },
    blog: { subtitle: 'Guide Golf Catalogne', title: 'Conseils, Guides de Parcours & Voyages', description: 'Conseils d\'experts en voyages de golf, guides d\u00e9taill\u00e9s de parcours et informations privil\u00e9gi\u00e9es pour planifier vos vacances de golf en Catalogne.', readMore: 'Lire la suite', noPosts: 'Pas encore de publications. Revenez bient\u00f4t !' },
    scroll: 'D\u00e9filer'
  },
  sv: {
    nav: { courses: 'Golfbanor', about: 'Om oss', contact: 'Kontakt', blog: 'Blogg', bookCta: 'Boka Tee Time' },
    hero: { title1: 'Boka Golf Tee Times', title2: 'i Katalonien', subtitle: '20 f\u00f6rstklassiga golfbanor fr\u00e5n Barcelona till Costa Brava. M\u00e4sterskapsbanor, kustjuveler och bergsretreat. Green fees fr\u00e5n 35 EUR.', cta: 'Utforska Golfbanor' },
    about: { subtitle: 'Din port till Golf i Katalonien', description: 'Katalonien \u00e4r hem f\u00f6r n\u00e5gra av Europas mest spektakul\u00e4ra golfbanor, fr\u00e5n det v\u00e4rldsber\u00f6mda Camiral Resort (tidigare PGA Catalunya) till g\u00f6mda p\u00e4rlor l\u00e4ngs Costa Brava. Med 20 banor i Barcelona, Girona, Tarragona och Pyren\u00e9erna g\u00f6r vi det enkelt att boka din perfekta runda.', feat1Title: '20 Premiumbanor', feat1Text: 'M\u00e4sterskapsbanor, kustbanor och bergsretreat i hela Katalonien.', feat2Title: 'Omedelbar Bekr\u00e4ftelse', feat2Text: 'Boka online och f\u00e5 omedelbar bekr\u00e4ftelse. Ingen v\u00e4ntan, inga samtal.', feat3Title: 'B\u00e4sta Pris Garanti', feat3Text: 'Vi f\u00f6rhandlar direkt med banorna f\u00f6r att erbjuda de b\u00e4sta green fee-priserna. Fr\u00e5n 35 EUR.' },
    courses: { title: 'Golfbanor i Katalonien', subtitle: 'Fr\u00e5n Barcelona till Pyren\u00e9erna \u2013 uppt\u00e4ck och boka tee times p\u00e5 regionens b\u00e4sta banor.', holes: 'H\u00e5l', par: 'Par', hover: 'Hovra f\u00f6r detaljer', bookBtn: 'Boka Tee Time', detailsBtn: 'Visa Bandetaljer' },
    cta: { title: 'Redo att spela?', subtitle: 'V\u00e4lj bland 20 premiumbanor i Katalonien. Omedelbar bekr\u00e4ftelse, b\u00e4sta priser och lokal expertis.', bookBtn: 'Boka Tee Time', contactBtn: 'Kontakta oss' },
    contact: { title: 'Kontakta oss', email: 'E-post', phone: 'Telefon', location: 'Plats' },
    footer: { description: 'Boka golf tee times i Katalonien med l\u00e4tthet. Vi t\u00e4cker alla golfregioner inklusive Barcelona, Costa Brava, Girona, Tarragona och Pyren\u00e9erna \u2013 20 premiumbanor inom r\u00e4ckh\u00e5ll.', quickLinks: 'Snabbl\u00e4nkar', services: 'Tj\u00e4nster', contactInfo: 'Kontaktinfo', home: 'Hem', golfCourses: 'Golfbanor', bookTee: 'Boka Tee Times i Katalonien', copyright: 'Alla r\u00e4ttigheter f\u00f6rbeh\u00e5llna.', privacy: 'Integritetspolicy', terms: 'Anv\u00e4ndarvillkor' },
    cookie: { text: 'Denna webbplats anv\u00e4nder cookies f\u00f6r att s\u00e4kerst\u00e4lla b\u00e4sta upplevelsen.', learn: 'L\u00e4s mer', accept: 'Acceptera', prefs: 'Inst\u00e4llningar' },
    blog: { subtitle: 'Katalonien Golfguide', title: 'Tips, Banguider & Reser\u00e5d', description: 'Expertgolfresetips, detaljerade banguider och insidertips f\u00f6r att planera din perfekta Katalonien-golfsemester.', readMore: 'L\u00e4s mer', noPosts: '\u00c4nnu inga inl\u00e4gg. Kom tillbaka snart!' },
    scroll: 'Scrolla'
  }
};

export default TRANSLATIONS;
